server:
  port: ${PORT:4000}

spring:
  datasource:
    url: jdbc:dbeaver:libsql:${TURSO_DATABASE_URL}
    username: token
    password: ${TURSO_AUTH_TOKEN}
    driver-class-name: com.dbeaver.jdbc.driver.libsql.LibSqlDriver
    hikari:
      isolate-internal-queries: false
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

pusher:
  app-id: ${PUSHER_APP_ID}
  key: ${PUSHER_KEY}
  secret: ${PUSHER_SECRET}
  cluster: ${PUSHER_CLUSTER}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: ${JWT_EXPIRATION:86400000}
