server:
  port: ${PORT:4000}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mariadb://localhost:3306/inventori_lab}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:alif}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: ${JWT_EXPIRATION:86400000}
